#!/bin/bash

echo "MongoDB Atlas Connection Troubleshooting"
echo "========================================"
echo ""
echo "Step 1: Verify your .env file has the correct format"
echo "Expected format: mongodb+srv://username:password@cluster.mongodb.net/database"
echo ""
echo "Step 2: Checklist for MongoDB Atlas:"
echo ""
echo "[ ] 1. Go to MongoDB Atlas Dashboard"
echo "[ ] 2. Select your cluster (justicechain)"
echo "[ ] 3. Click 'Database Access'"
echo "[ ] 4. Find user 'jananikaavya1104_db_user'"
echo "        - If NOT found: Create new database user"
echo "        - If found: Verify status is ACTIVE (green)"
echo ""
echo "[ ] 5. Go to 'Network Access'"
echo "[ ] 6. Verify your IP is whitelisted"
echo "        - Add 0.0.0.0/0 for development (allows all IPs)"
echo "        - Wait 1-2 minutes for changes to apply"
echo ""
echo "[ ] 7. Go to 'Clusters' → 'Connect'"
echo "[ ] 8. Click 'Drivers' → 'Node.js'"
echo "[ ] 9. Copy the connection string with your username and password"
echo ""
echo "Step 3: Common Issues:"
echo ""
echo "Issue: Special characters in password"
echo "Solution: Use URL encoding"
echo "  Example: @ becomes %40, : becomes %3A"
echo "  Use: https://www.urlencoder.org/"
echo ""
echo "Issue: Authentication failed"
echo "Solution: Make sure you're using DATABASE USER password, not your account password"
echo ""
echo "Issue: Connection timeout"
echo "Solution: Whitelist your IP in Network Access"
echo ""
echo "To retry after fixing, run:"
echo "  npm run init-db"
